Traceback (most recent call last):
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ngcchk/miniconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ngcchk/miniconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation

%matplotlib.use("MacOSX")


# NOT EXACTLY WORKING USING INLINE

#%matplotlib inline

# work

# if nothing use TkAgg
#%matplotlib
#%matplotlib qt 
#%matplotlib tk 

# not exactly working
#%matplotlib gtk
# Warning: Cannot change to a different GUI toolkit: gtk. Using tk instead.

# not working

# %matplotlib TkAgg <-- not working see above default; even ""
# %matplotlib MacOS 
# %matplotlib macos 



fig = plt.figure()
ax = plt.axes(xlim=(0, 4), ylim=(-2, 2))
line, = ax.plot([], [], lw=3)

def init():
    line.set_data([], [])
    return line,

# why , ???

def animate(i):
    x = np.linspace(0, 4, 1000)
    y = np.sin(2 * np.pi * (x - 0.01 * i))
    line.set_data(x, y)
    return line,

anim = FuncAnimation(fig, animate,
                     init_func=init,
                     frames=1000,
                     interval=10,
                     blit=True)


anim.save('handon-c12-sine_wave.gif', writer='pillow')

# export value
'''
top=0.88,
bottom=0.11,
left=0.125,
right=0.9,
hspace=0.2,
wspace=0.2
'''
------------------

----- stderr -----
UsageError: Line magic function `%matplotlib.use("MacOSX")` not found.
------------------



